// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutorial_5.Data;

#nullable disable

namespace Tutorial_5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523115724_AddComponentNavigations")]
    partial class AddComponentNavigations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tutorial_5.Entity.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU0000001",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "24-core (8P+16E) desktop processor, up to 5.8 GHz",
                            Name = "Intel Core i9-13900K"
                        },
                        new
                        {
                            Code = "GPU0000001",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 2,
                            Description = "Flagship Ada Lovelace GPU with 24 GB GDDR6X memory",
                            Name = "NVIDIA GeForce RTX 4090"
                        },
                        new
                        {
                            Code = "RAM0000001",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 3,
                            Description = "Dual-channel DDR5 memory kit, 2x16GB, CL30",
                            Name = "AMD Radeon DDR5 32GB 6000MHz"
                        });
                });

            modelBuilder.Entity("Tutorial_5.Entity.ComponentManufactures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Intel",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices, Inc."
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        });
                });

            modelBuilder.Entity("Tutorial_5.Entity.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("Tutorial_5.Entity.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasMaxLength(5)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Pro",
                            Stock = 8,
                            Warranty = 48,
                            Weight = 15f
                        });
                });

            modelBuilder.Entity("Tutorial_5.Entity.PCComponents", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM0000001",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("Tutorial_5.Entity.Component", b =>
                {
                    b.HasOne("Tutorial_5.Entity.ComponentManufactures", "ComponentManufactures")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutorial_5.Entity.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufactures");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("Tutorial_5.Entity.PCComponents", b =>
                {
                    b.HasOne("Tutorial_5.Entity.Component", "Component")
                        .WithMany("PCsComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutorial_5.Entity.PC", "Pc")
                        .WithMany("PCsComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("Tutorial_5.Entity.Component", b =>
                {
                    b.Navigation("PCsComponents");
                });

            modelBuilder.Entity("Tutorial_5.Entity.ComponentManufactures", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tutorial_5.Entity.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tutorial_5.Entity.PC", b =>
                {
                    b.Navigation("PCsComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
